const login = require('./login') // 登陆接口
const register = require('./register') // 注册接口
const home = require('./home') //请求主页
const userIcon = require('./userIcon') // 更换用户头像
const dataSearch = require('./dataSearch') // 数据搜索功能
const changeUserInfo = require('./changeUserInfo') // 修改信息
const getTeamInfo = require('./getTeamInfo') // 获取球队信息
const getUserInfo = require('./getUserInfo') // 获取用户信息
const getTeamData = require('./getTeamData')
const joinFavouriteTeam = require('./joinFavouriteTeam')
const forumHomePage = require('./forumHomePage')
const forumSearch = require('./forumSearch')
const verificationCode = require('./verificationCode')
const forumFound = require('./forumFound')
const forumPage = require('./forumPage')
const followForum = require('./followForum')
const pbulishForum = require('./pbulishForum')
const getForumPage = require('./getForumPage')
const activationEmail = require('./activationEmail')
const getPlayerInfo = require('./getPlayerInfo')
const logout = require('./logout')
const forumPeply = require('./forumReply')
const forumUnfollow = require('./forumUnfollow')
const loadForumIcon = require('./forumIcon')
const forumCollect = require('./collectForum')
const attentionUser = require('./attentionUser')
const userCenter = require('./userCenter')
const userFriend = require('./userFriend')
const cancelAttentionUser = require('./cancelAttentionUser')
const userSuggest = require('./userSuggest')
const findTypeOfForum = require('./findTypeOfForum')
module.exports = (app) => {
    app.use(login)
    app.use(register)
    app.use(home)
    app.use(userIcon)
    app.use(dataSearch)
    app.use(changeUserInfo)
    app.use(getTeamInfo)
    app.use(getUserInfo)
    app.use(getTeamData)
    app.use(joinFavouriteTeam)
    app.use(forumHomePage)
    app.use(forumSearch)
    app.use(verificationCode)
    app.use(forumFound)
    app.use(forumPage)
    app.use(followForum)
    app.use(pbulishForum)
    app.use(getForumPage)
    app.use(activationEmail)
    app.use(getPlayerInfo)
    app.use(logout)
    app.use(forumPeply)
    app.use(forumUnfollow)
    app.use(loadForumIcon)
    app.use(forumCollect)
    app.use(attentionUser)
    app.use(userCenter)
    app.use(userFriend)
    app.use(cancelAttentionUser)
    app.use(userSuggest)
    app.use(findTypeOfForum)
}