const login = require('./login')
const register = require('./register')
const home = require('./home')
const userIcon = require('./userIcon')
const dataSearch = require('./dataSearch')
const changeUserInfo = require('./changeUserInfo')
const getTeamInfo = require('./getTeamInfo')
module.exports = (app) => {
    app.use(login)
    app.use(register)
    app.use(home)
    app.use(userIcon)
    app.use(dataSearch)
    app.use(changeUserInfo)
    app.use(getTeamInfo)
}